apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: textextractor
    yuuvis: "true"
  name: textextractor
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.textextractor.port}}
  selector:
    name: textextractor
  type: ClusterIP