apiVersion: v1
kind: Service
metadata:
  labels:
    name: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: "9300"
    port: {{.Values.elasticsearch.port}}
    targetPort: {{.Values.elasticsearch.targetPort}}
  - name: "9200"
    port: {{.Values.elasticsearch.port2}}
    targetPort: {{.Values.elasticsearch.targetPort2}}
  clusterIP: None
  selector:
    name: elasticsearch
    app: {{.Values.yuuvis.labels.app}}