apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: controller
    yuuvis: "true"
  name: controller
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.controller.port}}
  selector:
    name: controller
  type: ClusterIP