apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: search
    yuuvis: "true"
  name: search
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.search.port}}
  selector:
    name: search
  type: ClusterIP