apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mq
  labels:
    app: pvcs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/optimal/mq
    server: 10.0.1.51
