apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: index
    yuuvis: "true"
  name: index
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.index.port}}
  selector:
    name: index
  type: ClusterIP