apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gg
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp/optimal/gg
    server: 10.211.55.4
