apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gg
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/optimal/gg
    server: 10.0.1.51
