apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mq
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp/optimal/mq
    server: 10.0.1.51
