apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mi
  labels:
    app: pvcs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/optimal/mi
    server: 192.168.178.77
