{{- if .Values.yuuvis.services.archive.deploy }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: archive
    yuuvis: "true"
  name: archive
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.archive.port}}
  selector:
    name: archive
  type: ClusterIP
{{- end}}