apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: registry
    yuuvis: "true"
  name: registry
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.registry.port}}
  selector:
    name: registry
  type: ClusterIP