apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
  name: adminserviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adminrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discoveryrole
subjects:
- kind: ServiceAccount
  name: adminserviceaccount