apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: configservice
    yuuvis: "true"
  name: configservice
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.config.port}}
  selector:
    name: configservice
