apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-raid-blob-configmap
  namespace: {{ .Release.Namespace }}
data:
  csiraid.config: |
    [source]
    type = azureblob
    account = azurenfs3cloadstorage
    key = z2h7JY7GfvDmdhhUrNNBRAhAa+/26Zq/k52EP3sGqKqzK/hp7cwz2YMtXA9bvTzZXt0CoCXdKW676uQ6qC0Kwg==
    [target]
    type = sftp
    host = 192.168.178.77
    path = /mnt/optimal/nfs-csi-provisioner-backup
    user = root
    key_file = /.ssh/id_rsa
    md5sum_command = md5sum
    sha1sum_command = sha1sum

