apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: admin
    yuuvis: "true"
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.admin.port}}
  selector:
    name: admin 
  type: ClusterIP