apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: organization
    yuuvis: "true"
  name: organization
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.organization.port}}
  selector:
    name: organization
  type: ClusterIP