---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-blob
  labels:
    app: nginx
spec:
  serviceName: statefulset-blob
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: statefulset-blob
          image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
#          command: [ "/bin/sh", "-c" ]
#          args:
#            -
#              echo "check if my service is running and run commands";
#              touch "/mnt/blob/testdatei"
#              while true;
#                do echo $(date) >> /mnt/blob/outfile;
#                sleep 1;
#              done
          command:
            - "/bin/sh"
            - "-c"
            - while true; do echo $(date) >> /mnt/blob/outfile; touch /mnt/blob/testdatei; sleep 1; done
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/blob
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: blob
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 100Gi
