apiVersion: v1
kind: Secret
metadata:
  name: keycloakdb
type: Opaque
data:
  user: {{ .Values.yuuvis.keycloak.db.user | b64enc | quote }}
  password: {{ .Values.yuuvis.keycloak.db.password | b64enc | quote }}
  