imageCredentials:
  dockeryuuvisorg:
    registry: docker.yuuvis.org
    username: osvh
    password: j21xrx7xzGxYqvR

yuuvis:
  # !!! Change before running
  # replace the value with the namespace you intent to use for the yuuvis API services
  # this chart creates a k8s job that generatey a selfsigned certificate and deploys the
  # crt file as a secret to the given namespace
  namespaces: 
    yuuvis: yuuvis
    infrastructure: infrastructure
  authentication:
    # we assume test deployment in minikube
    # ip is the ip of the vm minikube creates
    # to get the ip: minikube ip
    ip: auth.momentum.tobbib.com
    port: 443
  labels:
    app: yuuvis
  db:
    user: yuuvis
    password: optimal
  keycloak:
    user: keycloak
    password: j21xrx7xzGxYqvR
    db:
      user: keycloak
      password: optimal
    nodePort: 30111
    realm:
      yuuvistest:
        user:
          name: root
          password: j21xrx7xzGxYqvR
      testyuuvis:
        user:
          name: root
          password: j21xrx7xzGxYqvR
    
elasticsearch:
  image: docker.yuuvis.org/yuuvis/elasticsearch:2021-02-09
  imagePullPolicy: IfNotPresent
  imagePullSecret: dockeryuuvisorg
  storage: 100Mi
  storageClassName: default
  javaOpts: -Xms1024m -Xmx1024m
  replicas: 1
  port: 9300
  targetPort: 9300
  port2: 9200
  targetPort2: 9200
  # value for the elastic parameter uster.initial_master_nodes
  # if more than 1 node should be used, adjust initial master nodes value
  initial_master_nodes: elasticsearch-0

postgresql:
  enabled: true
  fullnameOverride: postgresql
  postgresqlPassword: optimal
  persistence:
    storageClass: default
    size: 100Mi
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  initdbScriptsConfigMap: postgresql-initdb
  postgresqlExtendedConf: {"max_connections": "400", "shared_buffers": "128MB"}


rabbitmq:
  enabled: true
  fullnameOverride: rabbitmq
  auth:
    username: rodger
    password: optimal
  extraPlugins: "rabbitmq_auth_backend_ldap rabbitmq_amqp1_0 rabbitmq_prometheus"
  extraConfiguration: |-
    #default_vhost = {{ .Release.Namespace }}-vhost
    #disk_free_limit.absolute = 50MB
    #load_definitions = /app/load_definition.json
    amqp1_0.default_user = rodger
  persistence:
    enabled: true
    storageClass: default
    size: 100Mi

gogs:
  useCustomDeployment: true
  image: gogs/gogs:0.11.91
  imagePullPolicy: IfNotPresent
  initcontainer:
    image: docker.yuuvis.org/yuuvis/helper/init-helper:latest
    secret: dockeryuuvisorg
  persistence:
    size: 500Mi
    storageClassName: default
  git:
    user: yuuvis
    password: optimal
    
minio:
  enabled: true
  fullnameOverride: minio
  accessKey: "osvhstorageaccount"
  secretKey: "qLjsdzb3iSE2CC76hc/olPySdfok+yJfi4RmbkbvU5YhlRFlPTFPPCiKRGhtTiZEoNljosEOeF5+YQc8gZN5kQ=="
  persistence:
    storageClass: default
    size: 200Mi
  resources: {}
  # for gateway usage with azure blob storage set access  key and secret key to your
  # storage account credentials, activate azure gateway mode and disable persistence
  persistence:
    enabled: false
  azuregateway:
    enabled: true
    replicas: 1

keycloak:
  enabled: true
  fullnameOverride: "keycloak"
  image.repository: docker.yuuvis.org/yuuvis/keycloak
  image.tag: 11.0.2-stable1
  livenessProbe: |
    httpGet:
      path: /auth/
      port: http
    initialDelaySeconds: 600
    timeoutSeconds: 5
  postgresql:
    enabled: false
  extraEnv: |
    - name: KEYCLOAK_USER_FILE
      value: /secrets/keycloak/user
    - name: KEYCLOAK_PASSWORD_FILE
      value: /secrets/keycloak/password
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: postgresql
    - name: DB_PORT
      value: "5432"
    - name: DB_DATABASE
      value: keycloak
    - name: DB_USER_FILE
      value: /secrets/db-creds/user
    - name: DB_PASSWORD_FILE
      value: /secrets/db-creds/password
    - name: KEYCLOAK_IMPORT
      value: "/realm/yuuvistest.json,/realm/testyuuvis.json -Dkeycloak.profile.feature.upload_scripts=enabled"
  extraVolumes: |
    - name: realm-config
      configMap:
        name: realmconfigmap
    - name: keycloak-tls-localhost
      secret:
        defaultMode: 420
        secretName: keycloak-selfsigned-tls-secret
    - name: db-creds
      secret:
        secretName: keycloakdb
    - name: kc-creds
      secret:
        secretName: keycloakuser
  extraVolumeMounts: |
    - name: realm-config
      mountPath: "/realm/"
      readOnly: true
    - name: keycloak-tls-localhost
      mountPath: "/etc/x509/https/"
    - name: db-creds
      mountPath: /secrets/db-creds
      readOnly: true
    - name: kc-creds
      mountPath: /secrets/keycloak
      readOnly: true

redis:
  fullnameOverride: redis
  ## Cluster settings
  cluster:
    enabled: false
  usePassword: false
  master:
    livenessProbe:
      initialDelaySeconds: 600
    persistence:
      enabled: false
      storageClass: default
      size: 50Mi
