apiVersion: v1
kind: Secret
metadata:
  name: bpm-dbsecret
type: Opaque
data:
  user: {{ .Values.yuuvis.bpm.engine.database.user | b64enc | quote }}
  password: {{ .Values.yuuvis.bpm.engine.database.password | b64enc | quote }}