# ./playbooks/persistentvolumes/pvs.yml

- name: install persistent volumes
  hosts: localhost
  vars_files:
  - "./playbooks/vars/{{ env }}.yml"
#  pre_tasks:
#    - name: include env vars
#
#      include_vars: "{{ env }}.yml"
#      tags: ["always"]
  tasks:
  - name: install pv-es
    shell: kubectl apply -f ./playbooks/persistentvolumes/pv-es.yml
    args:
      chdir: "{{ installdir }}"
  - name: install pv-mi
    shell: kubectl apply -f ./playbooks/persistentvolumes/pv-gg.yml
    args:
      chdir: "{{ installdir }}"
  - name: install pv-mi
    shell: kubectl apply -f ./playbooks/persistentvolumes/pv-mi.yml
    args:
      chdir: "{{ installdir }}"
  - name: install pv-mi
    shell: kubectl apply -f ./playbooks/persistentvolumes/pv-mq.yml
    args:
      chdir: "{{ installdir }}"
  - name: install pv-mi
    shell: kubectl apply -f ./playbooks/persistentvolumes/pv-pg.yml
    args:
      chdir: "{{ installdir }}"
