---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob
provisioner: blob.csi.azure.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: azure-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: azure-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
mountOptions:
#  - -o gid=1000
  - -o allow_other
  - --file-cache-timeout-in-seconds=720
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=720  # prevent billing charges on mounting
  - -o attr_timeout=720
  - -o entry_timeout=720
  - -o negative_timeout=720
  - --log-level=LOG_DEBUG  # LOG_WARNING, LOG_INFO, LOG_DEBUG
  - --cache-size-mb=1000  # Default will be 80% of available memory, eviction will happen beyond that.
