apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-raid-storage
provisioner: jw-cloud.org/csi-raid # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
