apiVersion: v1
appVersion: "1.0"
description: umbrella chart with examples for infrastructure components of an yuuvis API installation
             infrastructure components include a database, an identity provider, storage etc.
             this chart is for demo use only 
             do not use this chart for production
name: infrastructure
version: 0.8.0
