apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pg
  labels:
    app: pvcs
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/optimal/pg
    server: 192.168.178.77
