- name: create infrastructure and waiting suppression ending
  community.kubernetes.helm:
    name: infrastructure
    release_namespace: infrastructure
    chart_ref: ../yuuvis/infrastructure
    kubeconfig_path: "{{ kubeconfig }}"
    create_namespace: true
    wait: true
    values:
      yuuvis:
        authentication:
          ip: "{{ hostIP }}"
          port: "{{ hostPort }}"
        db:
          password: "{{ dbpassword }}"
        keycloak:
          password: "{{ keycloakpassword }}"
          db:
            password: "{{ keycloakdbpassword }}"
          realm:
            yuuvistest:
              user:
                password: "{{ keycloakrealmyuuvistestuserpassword }}"
            testyuuvis:
              user:
                password: "{{ keycloakrealmtestyuuvisuserpassword }}"
      elasticsearch:
        storage: "{{ elasticsearchstorage }}"
        storageClassName: "{{ elasticsearchstorageClassName }}"
      postgresql:
        postgresqlPassword: "{{ postgresqlPassword }}"
        persistence:
          storageClass: "{{ postgresqlpersistencestorageClass }}"
          size: "{{ postgresqlpersistencesize }}"
        volumePermissions:
          securityContext:
            runAsUser: "auto"
        securityContext:
            enabled: false
        containerSecurityContext:
            enabled: false
        shmVolume:
            chmod:
              enabled: false
      rabbitmq:
        auth:
          password: "{{ rabbitmqauthpassword }}"
        persistence:
          storageClass: "{{ rabbitmqpersistencestorageClass }}"
          size: "{{ rabbitmqpersistencesize }}"
      gogs:
        persistence:
          storageClassName: "{{ gogspersistencestorageClassName }}"
          size: "{{ gogspersistencesize }}"
        git:
          password: "{{ gogsgitpassword }}"
      gitea:
        enabled: true
        fullnameOverride: gitea
        ingress:
          enabled: true
        gitea:
          admin:
            password: optimalsystem
          config:
            database:
              DB_TYPE: sqlite3
              ## https://gitea.com/gitea/helm-chart/issues/95#issuecomment-122875
              ## Note that the intit script checks to see if the IP & port of the database service is accessible, so make sure you set those to something that resolves as successful (since sqlite uses files on disk setting the port & ip won't affect the running of gitea).
              HOST: example.com
              PORT: 80
            service:
              DISABLE_REGISTRATION: true
          database:
            builtIn:
              postgresql:
                enabled: false
          cache:
            builtIn:
              enabled: false
        persistence:
          enabled: true
          size: 1Gi
          storageClassName: managed-nfs-raid-storage
      minio:
        accessKey: "{{ minioaccessKey }}"
        secretKey: "{{ miniosecretKey }}"
        persistence:
          storageClass: "{{ miniopersistencestorageClass }}"
          size: "{{ miniopersistencesize }}"
          enabled: "{{ miniopersistenceenabled }}"
        azuregateway:
          enabled: "{{ minioazuregatewayenabled }}"
      redis:
        master:
          persistence:
            storageClass: "{{ redismasterpersistencestorageClass }}"

- name: create yuuvis and waiting suppression ending
  community.kubernetes.helm:
    name: yuuvis
    release_namespace: yuuvis
    chart_ref: ../yuuvis/yuuvis
    kubeconfig_path: "{{ kubeconfig }}"
    create_namespace: true
    wait_timeout: "15m"
    wait: true
    values:
      yuuvis:
        keycloak:
          address: "{{ keycloakAddress }}"
        git:
          password: "{{ yuuvisgitpassword }}"
        amqp:
          password: "{{ yuuvisamqppassword }}"
        db:
          password: "{{ yuuvisdbpassword }}"
        storage: |
          storage:
            repositories:
              s3:
                profiles: ['s3profile1']
                default: true
              netapp:
                profiles: ['netapplike']
                url:  http://archive/api/profiles/{profile}/dms/objects
                useDiscovery: true
            profiles:
              s3:
                s3profile1:
                  access-key: "{{ yuuvisstoragestorageprofiless3s3profile1accesskey }}"
                  secret-key: "{{ yuuvisstoragestorageprofiless3s3profile1secretkey }}"
                  url: 'http://minio.infrastructure:9000'
                  bucket: 'dmscloudrepodocker'
              netapp:
                netapplike:
                  # use mountpoint of the persistent volume claim that provides the netapp storage
                  # must be the same in the deployment of the archive app
                  volume: '/var/lib/netapp/data'
                  defaultRetentionInDays: 10
        oauth2: |
          # configuration for the yuuvis authentication service
          # im variablennamen in einer configmap darf kein Punkt stehen!!!
          keycloak.host: {{ keycloakAddress }}
          authentication.filter: oauth2
          authentication.provider: oauth2
          authentication.exposed.endpoints: ''
          authentication.oauth2.tenants:
          - name: yuuvistest
            clientId: yuuvis-authentication-service
            clientSecret: dbdf4856-3c86-4e5f-aca7-96f3d93d35b4
            userAuthorizationUri: https://${keycloak.host}/auth/realms/yuuvistest/protocol/openid-connect/auth
            accessTokenUri: https://${keycloak.host}/auth/realms/yuuvistest/protocol/openid-connect/token
            userInfoUri: https://${keycloak.host}/auth/realms/yuuvistest/protocol/openid-connect/userinfo
            endSessionUri: https://${keycloak.host}/auth/realms/yuuvistest/protocol/openid-connect/logout?redirect_uri=${redir}
            userNameExtractionPattern: $.sub
          - name: testyuuvis
            clientId: yuuvis-authentication-service
            clientSecret: 61048b73-8cd7-4682-b78c-786c5dc8a2a1
            userAuthorizationUri: https://${keycloak.host}/auth/realms/testyuuvis/protocol/openid-connect/auth
            accessTokenUri: https://${keycloak.host}/auth/realms/testyuuvis/protocol/openid-connect/token
            userInfoUri: https://${keycloak.host}/auth/realms/testyuuvis/protocol/openid-connect/userinfo
            endSessionUri: https://${keycloak.host}/auth/realms/testyuuvis/protocol/openid-connect/logout?redirect_uri=${redir}
            userNameExtractionPattern: $.sub
          # configuration for the yuuvis organization service
          keycloak.server: https://keycloak-https.infrastructure/auth
          keycloak.admin.username: keycloak
          keycloak.admin.password: "{{ yuuvisoauth2keycloakadminpassword }}"
        services:
          api:
            tag: "{{ yuuvisservicesapitag }}"
          admin:
            tag: "{{ yuuvisservicesadmintag }}"
          audit:
            tag: "{{ yuuvisservicesaudittag }}"
          authentication:
            tag: "{{ yuuvisservicesauthenticationtag }}"
          config:
            tag: "{{ yuuvisservicesconfigtag }}"
          contentanalyzer:
            tag: "{{ yuuvisservicescontentanalyzertag }}"
          index:
            tag: "{{ yuuvisservicesindextag }}"
          organization:
            tag: "{{ yuuvisservicesorganizationtag }}"
          registry:
            tag: "{{ yuuvisservicesregistrytag }}"
          repository:
            tag: "{{ yuuvisservicesrepositorytag }}"
          search:
            tag: "{{ yuuvisservicessearchtag }}"
          system:
            tag: "{{ yuuvisservicessystemtag }}"
- name: create client and waiting suppression ending
  community.kubernetes.helm:
    name: client
    release_namespace: yuuvis
    chart_ref: ../yuuvis/client
    kubeconfig_path: "{{ kubeconfig }}"
    wait: true
    values:
      yuuvis:
        git:
          password: "{{ clientgitpassword }}"
        amqp:
          password: "{{ clientamqppassword }}"
        client:
          userservice:
            database:
              password: "{{ clientclientuserservicedatabasepassword }}"
              privilege:
                password: "{{ clientclientuserservicedatabaseprivilegepassword }}"
            userserviceyml: |
              keycloak.server: http://keycloak-http.infrastructure/auth
              keycloak.admin.username: keycloak
              keycloak.admin.password: "{{ clientclientuserserviceuserserviceymlkeycloakadminpassword }}"
          client:
            dockerImage: "{{ clientclientdockerImage }}"
          custom:
            dockerImage: "{{ clientcustomdockerImage }}"
- name: restart api
  shell: kubectl rollout restart deployment api -n yuuvis --kubeconfig={{ kubeconfig }} -v=6
- name: create bpm and waiting suppression ending
  community.kubernetes.helm:
    name: bpm
    release_namespace: yuuvis
    chart_ref: ../yuuvis/bpm
    kubeconfig_path: "{{ kubeconfig }}"
    wait: true
    values:
      yuuvis:
        bpm:
          engine:
            database:
              password: "{{ bpmenginedatabasepassword }}"
              privilege:
                password: "{{ bpmenginedatabaseprivilegepassword }}"
- name: create rendition and waiting suppression ending
  community.kubernetes.helm:
    name: rendition
    release_namespace: yuuvis
    chart_ref: ../yuuvis/rendition
    kubeconfig_path: "{{ kubeconfig }}"
    wait: true
    values:
      yuuvis:
        renditionservice:
          dockerImage: "{{ renditionyuuvisrenditionservicedockerImage }}"
- name: create management and waiting suppression ending
  community.kubernetes.helm:
    name: management
    release_namespace: yuuvis
    chart_ref: ../yuuvis/management
    kubeconfig_path: "{{ kubeconfig }}"
    wait_timeout: "15m"
    wait: true
    values:
      yuuvis:
        apitm:
          client:
            rooturl: "{{ managementapitmclientrooturl }}"
        management:
          console:
            api:
              config:
                db:
                  password: "{{ managementmanagementconsoleapiconfigdbpassword }}"
                  privilege:
                    user: "{{ managementmanagementconsoleapiconfigdbprivilegeuser }}"
                    password: "{{ managementmanagementconsoleapiconfigdbprivilegepassword }}"


