- hosts: localhost
  vars:
    helm_chart_gitea_url: "https://dl.gitea.io/charts/"
  tasks:
    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: gitea-charts
        repo_url: "{{ helm_chart_gitea_url }}"
    - name: Update repo cach
      kubernetes.core.helm:
        name: dummy
        namespace: infrastructure
        state: absent
        update_repo_cache: true
    - name: Install gitea
      kubernetes.core.helm:
        name: gitea
        namespace: infrastructure
        chart_ref: gitea-charts
        wait: True
