- hosts: master
  tasks:
    - name: create directories to be mounted
      become: true
      file:
        path: '{{ item }}'
        state: directory
        owner: root
        group: root
        mode: 0777
      with_lines: cat "{{ mountdirs }}"
- hosts: localhost
  tasks:
    - name: create infrastructure and waiting suppression ending
      import_tasks: ./updateTask.yml
