---
- hosts: localhost
  tasks:
    - name: DeInstall Nginx Chart
      kubernetes.core.helm:
        name: nginx-server
        state: absent
        namespace: testing
        chart_ref: bitnami/nginx
        create_namespace: True
    - name: DeInstall postgresql Chart
      kubernetes.core.helm:
        name: postgresql
        state: absent
        namespace: testing
        chart_ref: bitnami/postgresql
        create_namespace: True