apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pg
  labels:
    app: pvcs
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/optimal/pg
    server: 10.0.1.51
