- hosts: localhost
  tasks:
    - name: Install elasticsearch
      kubernetes.core.helm:
        name: elasticsearch
        state: absent
        namespace: kube-system
        chart_ref: elastic/elasticsearch
        kubeconfig_path: "{{ kubeconfig }}"
        create_namespace: True
        wait: true
        values_files: $HOME/workspace/yuuvis/elk/elasticsearch/values.yaml
