- hosts: master
  become: yes
  tasks:
    - name: create .kube/minio directory
      become: yes
      become_user: jwewer
      file:
        path: $HOME/.kube/minio
        state: directory
        mode: 0755
    - name: copy pv-es from controll to host
      copy:
        src: minio/pv-es.yml
        dest: /home/jwewer/.kube/minio/pv-es.yml
        remote_src: no
        owner: jwewer
    - name: install pv-es
      become: yes
      become_user: jwewer
      shell: kubectl apply -f /home/jwewer/.kube/minio/pv-es.yml
      args:
        chdir: $HOME
    - name: copy pv-gg from controll to host
      copy:
        src: minio/pv-gg.yml
        dest: /home/jwewer/.kube/minio/pv-gg.yml
        remote_src: no
        owner: jwewer
    - name: install pv-gg
      become: yes
      become_user: jwewer
      shell: kubectl apply -f /home/jwewer/.kube/minio/pv-gg.yml
      args:
        chdir: $HOME
    - name: copy pv-mi from controll to host
      copy:
        src: minio/pv-mi.yml
        dest: /home/jwewer/.kube/minio/pv-mi.yml
        remote_src: no
        owner: jwewer
    - name: install pv-mi
      become: yes
      become_user: jwewer
      shell: kubectl apply -f /home/jwewer/.kube/minio/pv-mi.yml
      args:
        chdir: $HOME
    - name: copy pv-mq from controll to host
      copy:
        src: minio/pv-mq.yml
        dest: /home/jwewer/.kube/minio/pv-mq.yml
        remote_src: no
        owner: jwewer
    - name: install pv-mq
      become: yes
      become_user: jwewer
      shell: kubectl apply -f /home/jwewer/.kube/minio/pv-mq.yml
      args:
        chdir: $HOME
    - name: copy pv-pg from controll to host
      copy:
        src: minio/pv-pg.yml
        dest: /home/jwewer/.kube/minio/pv-pg.yml
        remote_src: no
        owner: jwewer
    - name: install pv-pg
      become: yes
      become_user: jwewer
      shell: kubectl apply -f /home/jwewer/.kube/minio/pv-pg.yml
      args:
        chdir: $HOME

