- hosts: master
  tasks:
    - name: Include task nfs dependencies
      import_tasks: ./nfs/master.yaml

- hosts: workers
  tasks:
    - name: Include task nfs dependencies
      import_tasks: ./nfs/workers.yaml

- hosts: localhost
  tasks:
    - name: create persistent volumes
      shell: kubectl apply -f '{{ item }}'
      args:
        chdir: "{{ installdir }}"
      with_lines: cat "{{ persistentvolumeslist }}"
    - name: create infrastructure and waiting suppression ending
      community.kubernetes.helm:
        name: infrastructure
        release_namespace: infrastructure
        chart_ref: $HOME/workspace/yuuvis/infrastructure
        create_namespace: true
        wait: true
    - name: create yuuvis and waiting suppression ending
      community.kubernetes.helm:
        name: yuuvis
        release_namespace: yuuvis
        chart_ref: $HOME/workspace/yuuvis/yuuvis
        create_namespace: true
        wait_timeout: "10m"
        wait: true
    - name: create client and waiting suppression ending
      community.kubernetes.helm:
        name: client
        release_namespace: yuuvis
        chart_ref: $HOME/workspace/yuuvis/client
        wait: true
    - name: restart api
      shell: kubectl rollout restart deployment api -n yuuvis
    - name: create bpm and waiting suppression ending
      community.kubernetes.helm:
        name: bpm
        release_namespace: yuuvis
        chart_ref: $HOME/workspace/yuuvis/bpm
        wait: true
