apiVersion: v1
kind: Secret
metadata:
  name: azure-cloud-provider
  namespace: kube-system
type: Opaque
stringData:
  cloud-config: |
    vnetResourceGroup: "csiraid"
    vnetName: "azurenfs3cloadstorage_vNet129929"
    subnetName: "default"
