- hosts: localhost
  vars:
    application: true
  tasks:
  - name: Remove management and waiting suppression ending
    community.kubernetes.helm:
      name: management
      release_namespace: yuuvis
      kubeconfig_path: "{{ kubeconfig }}"
      state: absent
      wait: true
    when: application
  - name: Remove rendition and waiting suppression ending
    community.kubernetes.helm:
      name: rendition
      release_namespace: yuuvis
      kubeconfig_path: "{{ kubeconfig }}"
      state: absent
      wait: true
    when: application
  - name: Remove bpm and waiting suppression ending
    community.kubernetes.helm:
      name: bpm
      release_namespace: yuuvis
      kubeconfig_path: "{{ kubeconfig }}"
      state: absent
      wait: true
    when: application
  - name: Remove client and waiting suppression ending
    community.kubernetes.helm:
      name: client
      release_namespace: yuuvis
      kubeconfig_path: "{{ kubeconfig }}"
      state: absent
      wait: true
    when: application
  - name: Remove yuuvis and waiting suppression ending
    community.kubernetes.helm:
      name: yuuvis
      release_namespace: yuuvis
      kubeconfig_path: "{{ kubeconfig }}"
      state: absent
      wait: true
    when: application
  - name: Remove infrastructure and waiting suppression ending
    community.kubernetes.helm:
      name: infrastructure
      release_namespace: infrastructure
      kubeconfig_path: "{{ kubeconfig }}"
      state: absent
      wait: true
    when: application
  - name: delete dynamic storage provisioner
    import_tasks: ./dynamicStorageProvisionerDelete.yml
