- hosts: master
  tasks:
    - name: Include task nfs dependencies
      import_tasks: ./nfs/master.yaml

- hosts: workers
  tasks:
    - name: Include task nfs dependencies
      import_tasks: ./nfs/workers.yaml

- hosts: localhost
  tasks:
    - name: create persistent volumes
      shell: kubectl apply -f '{{ item }}'
      args:
        chdir: "{{ installdir }}"
      with_lines: cat "{{ persistentvolumeslist }}"
    - name: create nfs provisioner
      community.kubernetes.helm:
        name: nfsprovisioner
        release_namespace: default
        chart_ref: $HOME/workspace/yuuvis/nfs-provisioner
        wait: true
        values:
          nfsProvisioner:
            nfsServer:
              ip: "{{ nfsserver }}"
              path: "{{ nfsprovisionerpath }}"
    - name: create infrastructure and waiting suppression ending
      import_tasks: ./updateTask.yml
