{
  "objects": [{
    "properties": {
      "system:objectTypeId": {
        "value": "tenYuuvistest:fallakteneodokument"
      },
      "system:parentId": {
        "value": "2d785e4a-a762-4838-ac0c-9268c2705df2"
      },
      "clienttitle": {
        "value": "clienttitlevalue"
      },
      "clientdescription": {
        "value": "clientdescriptionvalue"
      },
      "registertyp": {
        "value": "registertypvalue"
      },
      "dokumenttyp": {
        "value": "dokumenttypvalue"
      },
      "vorname": {
        "value": "vornamevalue"
      },
      "nachname": {
        "value": "nachnamevalue"
      },
      "vorlage": {
        "value": "vorlagevalue"
      },
      "erstelldatum": {
        "value": "erstelldatumvalue"
      },
      "kennung": {
        "value": "kennungvalue"
      },
      "id": {
        "value": "idvalue"
      },
      "geburtsdatum": {
        "value": "geburtsdatumvalue"
      },
      "dateiname": {
        "value": "dateinamevalue"
      },
      "adresse": {
        "value": "adressevalue"
      }
    }
  }
  ]
}
